services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: todo_backend
    environment:
      - DATABASE_URL=sqlite:///./database/todos.db
    volumes:
      - ./app:/app/app
      - ./database:/app/database
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: todo_frontend
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - BACKEND_URL=http://backend:8000
    ports:
      - "8501:8501"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  database_data:
    driver: local

networks:
  default:
    name: todo_network